default_expire_days: 90
string_blacklist:
  - resource

border_size_base: 10
border_expansion_max: 6

# プレイヤーデータ
default_unlocked_warp_slot: 3
default_unlocked_world_slot: 2

player_warp_slot_max: 10
player_world_slot_max: 3

global_world_count_max: 40

oage_ganbaru_message:
  - よいしょ！

escape_world: "world"
escape_pos: "(0, 0, 0)"

cancel_flag: "_cancel"

min_world_name_length: 3,
max_world_name_length: 10,

