name: MyWorldManager
version: '1.0-SNAPSHOT'
main: me.awabi2048.mw_manager.Main
api-version: '1.21'
softdepend:
  - Multiverse-Core

permissions:
  mw_manager.admin:
    description: "admin"
    children:
      - mw_manager.command.register_world
      - mw_manager.command.update_world
      - mw_manager.command.check_world_updated

  mw_manager.command.main:
    description: "/mwm"

  mw_manager.command.invite:
    description: "/invite"

  mw_manager.command.visit:
    description: "/visit"

  mw_manager.command.worldpoint:
    description: "/worldpoint"

  mw_manager.command.worldmenu:
    description: "/worldmenu"

  mw_manager.command.worldwarp:
    description: "/worldwarp"

commands:
  myworldmanager:
    description: ""
    aliases:
      - mwm
      - mwmanager

  invite:
    description: ""

  visit:
    description: ""

  worldmenu:
    description: ""

  worldpoint:
    description: ""

  warp:
    description: ""

  mwm_invite_accept:
    description: ""

  mwm_recruit_accept:
    description: ""