name: MyWorldManager
version: '1.0-SNAPSHOT'
main: me.awabi2048.mw_manager.Main
api-version: '1.21'
softdepend:
  - Multiverse-Core
depend:
  - ProtocolLib

permissions:
  mw_manager.admin:
    description: "admin"
    children:
      - mw_manager.command.mwm
      - mw_manager.command.world_point
      - mw_manager.citizen

  mw_manager.citizen:
    description: "user"
    children:
      - mw_manager.command.invite
      - mw_manager.command.visit
      - mw_manager.command.worldmenu
      - mw_manager.command.worldwarp
      - mw_manager.command.mwm_help
      - mw_manager.command.mwm_invite_accept
      - mw_manager.command.mwm_recruit_accept

  mw_manager.command.mwm:
    description: "/mwm"

  mw_manager.command.invite:
    description: "/invite"

  mw_manager.command.visit:
    description: "/visit"

  mw_manager.command.worldpoint:
    description: "/worldpoint"

  mw_manager.command.worldmenu:
    description: "/worldmenu"

  mw_manager.command.worldwarp:
    description: "/worldwarp"

  mw_manager.command.mwm_help:
    description: ""

  mw_manager.command.mwm_invite_accept:
    description: ""

  mw_manager.command.mwm_recruit_accept:
    description: ""


commands:
  myworldmanager:
    description: ""
    aliases:
      - mwm
      - mwmanager

  invite:
    description: ""

  visit:
    description: ""

  worldmenu:
    description: ""

  worldpoint:
    description: ""

  worldwarp:
    description: ""

  mwm_help:
    description: ""

  mwm_invite_accept:
    description: ""

  mwm_recruit_accept:
    description: ""

